name: Publish

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm and Install
        run: |
          npm install -g npm@latest
          npm ci

      - name: Build
        run: npm run lib-build
        env:
          # avoid fail on warnings
          CI: false

      - name: Publish on npmjs
        run: npm publish
